### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by vcsjones** [Spaxe/Goodbye--t.co-#1]
I would be really really interested in porting this to other browsers. Without a license, I'm unsure if I am able to do so. Can you please clarify under what license this code falls, and if I have permission to create a Safari extension from it?

**Comment by Spaxe** [comment]
Added Free Public License 1.0.0. Thanks @vcsjones. If you put your extensions up as open source, I would be happy to include links in `READNE.md`.
